spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://ADDRESS-SERVICES
          predicates:
            - Path=/address,/address/**,/save
        - id: api-2
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student,/student/**,/saveStu
server:
  port: 3333

